
:-(compiler_options([xpp_on,canonical])).

/********** Tabling and Trailer Control Variables ************/

#define EQUALITYnone
#define INHERITANCEflogic
#define TABLINGreactive
#define TABLINGvariant
#define CUSTOMnone

#define FLORA_INCREMENTAL_TABLING 

/************************************************************************
  file: headerinc/flrheader_inc.flh

  Author(s): Guizhen Yang

  This file is automatically included by the Flora-2 compiler.
************************************************************************/

:-(compiler_options([xpp_on])).
#mode standard Prolog

#include "flrheader.flh"
#include "flora_porting.flh"

/***********************************************************************/

/************************************************************************
  file: headerinc/flrheader_prog_inc.flh

  Author(s): Michael Kifer

  This file is automatically included by the Flora-2 compiler.
************************************************************************/

:-(compiler_options([xpp_on])).
#mode standard Prolog

#include "flrheader_prog.flh"

/***********************************************************************/

#define FLORA_COMPILATION_ID 8

#mode save
#mode nocomment "%"
#define FLORA_THIS_FILENAME  'utilities.flr'
#mode restore
:-(import(from(/(flora_warning_line,1),flrprint))).
?-(catch(abolish_all_tables,_,flora_warning_line('a tabled subgoal depends on ~w.~n		  The program might not function correctly.~n		  Offending file:    ~w~n		  Offending module:  ~w~n', ['\\add', FLORA_THIS_FILENAME, FLORA_THIS_MODULE_NAME]))).
/************************************************************************
  file: syslibinc/flrdynrule_inc.flh

  Author(s): Chang Zhao

  This file is automatically included by the FLORA-2 compiler.
************************************************************************/

:-(compiler_options([xpp_on])).

#mode standard Prolog

#if !defined(FLORA_TERMS_FLH)
#define FLORA_TERMS_FLH
#include "flora_terms.flh"
#endif

?-(:(flrlibman,flora_load_library(FLSYSRULEUPDATE))).

/***********************************************************************/

/************************************************************************
  file: syslibinc/flrload_inc.flh

  Author(s): Guizhen Yang

  This file is automatically included by the FLORA-2 compiler.
************************************************************************/

:-(compiler_options([xpp_on])).

#mode standard Prolog

#if !defined(FLORA_TERMS_FLH)
#define FLORA_TERMS_FLH
#include "flora_terms.flh"
#endif

?-(:(flrlibman,flora_load_library(FLLIBLOAD))).

/***********************************************************************/

/************************************************************************
  file: syslibinc/flrcolset_inc.flh

  Author(s): Guizhen Yang

  This file is automatically included by the FLORA-2 compiler.
************************************************************************/

:-(compiler_options([xpp_on])).

#mode standard Prolog

#if !defined(FLORA_TERMS_FLH)
#define FLORA_TERMS_FLH
#include "flora_terms.flh"
#endif

?-(:(flrlibman,flora_load_library(FLLIBCOLLECTSET))).

/***********************************************************************/

/************************************************************************
  file: syslibinc/flrdynrule_inc.flh

  Author(s): Chang Zhao

  This file is automatically included by the FLORA-2 compiler.
************************************************************************/

:-(compiler_options([xpp_on])).

#mode standard Prolog

#if !defined(FLORA_TERMS_FLH)
#define FLORA_TERMS_FLH
#include "flora_terms.flh"
#endif

?-(:(flrlibman,flora_load_library(FLSYSRULEUPDATE))).

/***********************************************************************/

/************************************************************************
  file: libinc/flrbasetype_inc.flh

  Author(s): Michael Kifer

  This file is automatically included by the Flora-2 compiler.
************************************************************************/

:-(compiler_options([xpp_on])).

#mode standard Prolog

#if !defined(FLORA_TERMS_FLH)
#define FLORA_TERMS_FLH
#include "flora_terms.flh"
#endif

?-(':'(flrlibman,flora_load_system_module(FLSYSMODBASETYPE))).

/***********************************************************************/

#ifndef FLORA_TABLING_METHODS_INCLUDED
#include "flora_tabling_methods.flh"
#endif
 
#if !defined(FLORA_FLD_FILENAME)
#if !defined(FLORA_LOADDYN_DATA)
#define FLORA_LOADDYN_DATA
#endif
#mode save
#mode nocomment "%"
#define FLORA_FLD_FILENAME  'utilities#for_add.fld'
#mode restore
?-(:(flrutils,flora_loaddyn_data(FLORA_FLD_FILENAME,FLORA_THIS_MODULE_NAME,'fld'))).
#else
#if !defined(FLORA_READ_CANONICAL_AND_INSERT)
#define FLORA_READ_CANONICAL_AND_INSERT
#endif
?-(:(flrutils,flora_read_canonical_and_insert(FLORA_FLD_FILENAME,FLORA_THIS_FLD_STORAGE))).
#endif

 
#if !defined(FLORA_FLS_FILENAME)
#if !defined(FLORA_LOADDYN_DATA)
#define FLORA_LOADDYN_DATA
#endif
#mode save
#mode nocomment "%"
#define FLORA_FLS_FILENAME  'utilities.fls'
#mode restore
?-(:(flrutils,flora_loaddyn_data(FLORA_FLS_FILENAME,FLORA_THIS_MODULE_NAME,'fls'))).
#else
#if !defined(FLORA_READ_CANONICAL_AND_INSERT)
#define FLORA_READ_CANONICAL_AND_INSERT
#endif
?-(:(flrutils,flora_read_symbols_canonical_and_insert(FLORA_FLS_FILENAME,FLORA_THIS_FLS_STORAGE,_SymbolErrNum))).
#endif


%%%%%%%%%%%%%%%%%%%%%%%%%%% Rule insertion statements %%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

?-(fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',3,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(load_instances,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibload([+('D://Flora//classroom_instances')],'C://Users//reslab//Documents//NetBeansProjects//pamthesis//src//java//timetable1//utilities.flr',FLORA_THIS_MODULE_NAME,[6,18]),','(fllibload([+('D://Flora//address_instances')],'C://Users//reslab//Documents//NetBeansProjects//pamthesis//src//java//timetable1//utilities.flr',FLORA_THIS_MODULE_NAME,[7,5]),','(fllibload([+('D://Flora//course_instances')],'C://Users//reslab//Documents//NetBeansProjects//pamthesis//src//java//timetable1//utilities.flr',FLORA_THIS_MODULE_NAME,[8,5]),','(fllibload([+('D://Flora//room_day_period_instances')],'C://Users//reslab//Documents//NetBeansProjects//pamthesis//src//java//timetable1//utilities.flr',FLORA_THIS_MODULE_NAME,[9,5]),','(fllibload([+('D://Flora//instances')],'C://Users//reslab//Documents//NetBeansProjects//pamthesis//src//java//timetable1//utilities.flr',FLORA_THIS_MODULE_NAME,[10,5]),','(fllibload([+('D://Flora//course_opening_instances')],'C://Users//reslab//Documents//NetBeansProjects//pamthesis//src//java//timetable1//utilities.flr',FLORA_THIS_MODULE_NAME,[11,5]),','(fllibload([+('D://Flora//CourseCodes')],'C://Users//reslab//Documents//NetBeansProjects//pamthesis//src//java//timetable1//utilities.flr',FLORA_THIS_MODULE_NAME,[12,5]),','(fllibload([+('D://Flora//course_opening_requests')],'C://Users//reslab//Documents//NetBeansProjects//pamthesis//src//java//timetable1//utilities.flr',FLORA_THIS_MODULE_NAME,[13,5]),fllibload([+('D://Flora//syllabus_instances')],'C://Users//reslab//Documents//NetBeansProjects//pamthesis//src//java//timetable1//utilities.flr',FLORA_THIS_MODULE_NAME,[14,5]))))))))),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?CO',__CO),=('?Year',__Year),=('?GroupNo',__GroupNo),=('?OfCourse',__OfCourse),=('?Semester',__Semester)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',4,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(pp_COs,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibsetof(__newdontcarevar11,[],','(','(=(__newdontcarevar11,1),','(','(FLORA_WORKSPACE(m1,d^isa)(__CO,'CourseOpening','_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar9,__newvar1)),','(FLORA_WORKSPACE(m1,d^mvd)(__CO,year,__Year,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),','(FLORA_WORKSPACE(m1,d^mvd)(__CO,groupNo,__GroupNo,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar6,__newvar1)),','(FLORA_WORKSPACE(m1,d^mvd)(__CO,ofCourse,__OfCourse,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar7,__newvar1)),FLORA_WORKSPACE(m1,d^mvd)(__CO,semester,__Semester,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar8,__newvar1)))))),FLORA_THIS_WORKSPACE(d^tblflapply)(pp_CO,__CO,__Year,__GroupNo,__OfCourse,__Semester,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar10,__newvar1)))),fllibexecute_delayed_calls([__CO,__GroupNo,__OfCourse,__Semester,__newdontcarevar11,__Year],[])),__newvar12),=(___x,__newvar12)),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[fllibexecute_delayed_calls([__CO,__GroupNo,__OfCourse,__Semester,__Year,___x],[])],true)]))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?GroupNo',__GroupNo),=('?OfCourse',__OfCourse),=('?Year',__Year),=('?Semester',__Semester),=('?CO',__CO),=('?TT',__TT),=('?Room',__Room),=('?Day',__Day),=('?Period',__Period),=('?Duration',__Duration)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?CO',__CO),=('?Year',__Year),=('?GroupNo',__GroupNo),=('?OfCourse',__OfCourse),=('?Semester',__Semester)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',5,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(pp_CO,__CO,__Year,__GroupNo,__OfCourse,__Semester,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(writeln('\\#:CourseOpening['),','(write('     groupNo ->'),','(write(__GroupNo),','(writeln(','),','(write('     ofCourse -> '),','(write(__OfCourse),','(writeln(','),','(write('     year -> '),','(write(__Year),','(writeln(','),','(write('     semester -> '),','(write(__Semester),','(writeln(','),','(','(fllibsetof(__newdontcarevar10,[],','(','(=(__newdontcarevar10,1),','(FLORA_WORKSPACE(m1,d^mvd)(__CO,teachingTimes,__TT,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),','(','(FLORA_WORKSPACE(m1,d^mvd)(__TT,room,__Room,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar6,__newvar1)),','(FLORA_WORKSPACE(m1,d^mvd)(__TT,day,__Day,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar7,__newvar1)),','(FLORA_WORKSPACE(m1,d^mvd)(__TT,period,__Period,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar8,__newvar1)),FLORA_WORKSPACE(m1,d^mvd)(__TT,duration,__Duration,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar9,__newvar1))))),','(write('     teachingTimes ->'),','(writeln('\\#['),','(write('              room -> '),','(write(__Room),','(write(','),','(nl,','(write('              day -> '),','(write(__Day),','(write(','),','(nl,','(write('              period -> '),','(write(__Period),','(write(','),','(nl,','(write('              duration -> '),','(write(__Duration),','(writeln('],'),','(nl,nl))))))))))))))))))))),fllibexecute_delayed_calls([__CO,__Day,__Duration,__Period,__Room,__TT,__newdontcarevar10],[])),__newvar11),=(___X,__newvar11)),writeln('].'))))))))))))))),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[fllibexecute_delayed_calls([__CO,__Day,__Duration,__GroupNo,__OfCourse,__Period,__Room,__Semester,__TT,__Year,___X],[__CO,__GroupNo,__OfCourse,__Semester,__Year])],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?X',__X),=('?Y',__Y)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?X',__X),=('?Y',__Y)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',6,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(member2,__X,[__Y|___A],'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],=(__X,__Y),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?X',__X),=('?R',__R)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?X',__X),=('?R',__R)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',7,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(member2,__X,[___H|__R],'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],FLORA_THIS_WORKSPACE(d^tblflapply)(member2,__X,__R,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?X',__X),=('?Y',__Y)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?X',__X),=('?Y',__Y)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',8,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(member3,__X,[__Y|___A],'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],=(__X,__Y),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?X',__X),=('?R',__R)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?X',__X),=('?R',__R)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',9,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(member3,__X,[___H|__R],'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],FLORA_THIS_WORKSPACE(d^nontblflapply)(member3,__X,__R,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar5,'\\$dynrule variable',[=('?X',__X),=('?Y',__Y)])),','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?X',__X),=('?Y',__Y)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',10,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(member5,__X,[','(__newdontcarevar2,','(__Y,','(___2,','(___3,___4))))|___A],'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar3))],','(=(__X,__Y),!),__newvar4,__newvar5,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar5,'\\$dynrule variable',[=('?X',__X),=('?Y',__Y)])),','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?X',__X),=('?Y',__Y)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',11,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(member5,__X,[','(__newdontcarevar2,','(___1,','(__Y,','(___3,___4))))|___A],'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar3))],','(=(__X,__Y),!),__newvar4,__newvar5,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar5,'\\$dynrule variable',[=('?X',__X),=('?Y',__Y)])),','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?X',__X),=('?Y',__Y)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',12,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(member5,__X,[','(__newdontcarevar2,','(___1,','(___2,','(__Y,___4))))|___A],'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar3))],','(=(__X,__Y),!),__newvar4,__newvar5,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar5,'\\$dynrule variable',[=('?X',__X),=('?Y',__Y)])),','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?X',__X),=('?Y',__Y)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',13,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(member5,__X,[','(__newdontcarevar2,','(___1,','(___2,','(___3,__Y))))|___A],'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar3))],','(=(__X,__Y),!),__newvar4,__newvar5,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?X',__X),=('?R',__R)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?X',__X),=('?R',__R)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',14,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(member5,__X,[___H|__R],'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],FLORA_THIS_WORKSPACE(d^tblflapply)(member5,__X,__R,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',15,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(printlist,[],'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],nl,__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?H',__H),=('?T',__T)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?H',__H),=('?T',__T)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',16,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(printlist,[__H|__T],'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(writeln(__H),FLORA_THIS_WORKSPACE(d^nontblflapply)(printlist,__T,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1))),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?L2',__L2),=('?L',__L)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?L',__L),=('?L2',__L2)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',17,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(app,[],__L,__L2,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],=(__L2,__L),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?H1',__H1),=('?H2',__H2),=('?T',__T),=('?L',__L),=('?T2',__T2)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?H1',__H1),=('?T',__T),=('?L',__L),=('?H2',__H2),=('?T2',__T2)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',18,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^tblflapply)(app,[__H1|__T],__L,[__H2|__T2],'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(=(__H1,__H2),FLORA_THIS_WORKSPACE(d^tblflapply)(app,__T,__L,__T2,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1))),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?L2',__L2),=('?L',__L)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?L',__L),=('?L2',__L2)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',19,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(appX,[],__L,__L2,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],=(__L2,__L),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?H1',__H1),=('?H2',__H2),=('?T',__T),=('?L',__L),=('?T2',__T2)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?H1',__H1),=('?T',__T),=('?L',__L),=('?H2',__H2),=('?T2',__T2)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',20,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(appX,[__H1|__T],__L,[__H2|__T2],'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(=(__H1,__H2),FLORA_THIS_WORKSPACE(d^nontblflapply)(appX,__T,__L,__T2,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1))),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?L2',__L2),=('?L1',__L1)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?L1',__L1),=('?L2',__L2)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',21,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(setSubtract,__L1,[],__L2,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(=(__L2,__L1),!),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?L1',__L1),=('?H',__H),=('?Temp',__Temp),=('?T',__T),=('?Result',__Result)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?L1',__L1),=('?H',__H),=('?T',__T),=('?Result',__Result)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',22,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(setSubtract,__L1,[__H|__T],__Result,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(FLORA_WORKSPACE(\\basetype,d^mvd)(__L1,flapply(delete,__H),__Temp,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),FLORA_THIS_WORKSPACE(d^nontblflapply)(setSubtract,__Temp,__T,__Result,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar6,__newvar1))),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[fllibexecute_delayed_calls([__H,__L1,__Result,__T,__Temp],[__H,__L1,__Result,__T])],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?Year1',__Year1),=('?Year2',__Year2)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?Year1',__Year1),=('?Year2',__Year2)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',23,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(semester_is_before,__Year1,___Semester1,__Year2,___Semester2,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(fllibdelayedliteral(<,'utilities.flr',82,[__Year1,__Year2]),!),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?Year1',__Year1),=('?Year2',__Year2),=('?Semester1',__Semester1),=('?Semester2',__Semester2)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?Year1',__Year1),=('?Semester1',__Semester1),=('?Year2',__Year2),=('?Semester2',__Semester2)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',24,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(semester_is_before,__Year1,__Semester1,__Year2,__Semester2,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(=(__Year1,__Year2),','(=(__Semester1,spring),','(';'(=(__Semester2,summer),=(__Semester2,fall)),!))),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?Year1',__Year1),=('?Year2',__Year2),=('?Semester1',__Semester1),=('?Semester2',__Semester2)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?Year1',__Year1),=('?Semester1',__Semester1),=('?Year2',__Year2),=('?Semester2',__Semester2)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',25,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(semester_is_before,__Year1,__Semester1,__Year2,__Semester2,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(=(__Year1,__Year2),','(=(__Semester1,summer),=(__Semester2,fall))),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?Y1',__Y1),=('?Y2',__Y2),=('?S1',__S1),=('?S2',__S2),=('?R',__R)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?Y1',__Y1),=('?S1',__S1),=('?Y2',__Y2),=('?S2',__S2),=('?R',__R)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',26,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(year_semester_subtract,__Y1,__S1,__Y2,__S2,__R,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(=(__Y1,__Y2),','(=(__S1,__S2),','(=(__R,0),!))),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?Y2',__Y2),=('?S2',__S2),=('?Y1',__Y1),=('?S1',__S1),=('?PrevYear',__PrevYear),=('?PrevSem',__PrevSem),=('?Temp',__Temp),=('?R',__R)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?Y1',__Y1),=('?S1',__S1),=('?Y2',__Y2),=('?S2',__S2),=('?R',__R)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',27,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(year_semester_subtract,__Y1,__S1,__Y2,__S2,__R,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(FLORA_THIS_WORKSPACE(d^nontblflapply)(semester_is_before,__Y2,__S2,__Y1,__S1,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),','(FLORA_THIS_WORKSPACE(d^nontblflapply)(get_sem_before,__Y1,__S1,__PrevYear,__PrevSem,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar6,__newvar1)),','(FLORA_THIS_WORKSPACE(d^nontblflapply)(year_semester_subtract,__PrevYear,__PrevSem,__Y2,__S2,__Temp,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar7,__newvar1)),fllibdelayedliteral('\\is','utilities.flr',103,[__R,+(__Temp,1)])))),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[fllibexecute_delayed_calls([__PrevSem,__PrevYear,__R,__S1,__S2,__Temp,__Y1,__Y2],[__R,__S1,__S2,__Y1,__Y2])],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?S1',__S1),=('?PrevSem',__PrevSem),=('?PrevYear',__PrevYear),=('?Y1',__Y1)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?Y1',__Y1),=('?S1',__S1),=('?PrevYear',__PrevYear),=('?PrevSem',__PrevSem)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',28,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(get_sem_before,__Y1,__S1,__PrevYear,__PrevSem,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(=(__S1,fall),','(!,','(=(__PrevSem,spring),=(__PrevYear,__Y1)))),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?S1',__S1),=('?PrevSem',__PrevSem),=('?PrevYear',__PrevYear),=('?Y1',__Y1)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?Y1',__Y1),=('?S1',__S1),=('?PrevYear',__PrevYear),=('?PrevSem',__PrevSem)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',29,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(get_sem_before,__Y1,__S1,__PrevYear,__PrevSem,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(=(__S1,spring),','(!,','(=(__PrevSem,fall),fllibdelayedliteral('\\is','utilities.flr',113,[__PrevYear,-(__Y1,1)])))),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?Course_CO_pair_list',__Course_CO_pair_list)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?Course_CO_pair_list',__Course_CO_pair_list)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',30,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(showCOs,__Course_CO_pair_list,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(=(__Course_CO_pair_list,[]),writeln(' ')),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?Course_CO_pair_list',__Course_CO_pair_list),=('?CourseCOPair',__CourseCOPair),=('?CourseCOPair_list',__CourseCOPair_list),=('?Course',__Course),=('?CO',__CO),=('?TeachingTimes',__TeachingTimes)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?Course_CO_pair_list',__Course_CO_pair_list)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',31,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(showCOs,__Course_CO_pair_list,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(=(__Course_CO_pair_list,[__CourseCOPair|__CourseCOPair_list]),','(=(__CourseCOPair,','(__Course,__CO)),','(FLORA_WORKSPACE(m1,d^isa)(__CO,'CourseOpening','_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),','(','(fllibsetof(__newdontcarevar7,[],','(FLORA_WORKSPACE(m1,d^mvd)(__CO,teachingTimes,__newdontcarevar7,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar6,__newvar1)),fllibexecute_delayed_calls([__CO,__newdontcarevar7],[])),__newvar8),=(__TeachingTimes,__newvar8)),','(write(-(__Course,' ')),','(FLORA_THIS_WORKSPACE(d^nontblflapply)(showTeachingTimes,__TeachingTimes,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar9,__newvar1)),','(writeln(' '),FLORA_THIS_WORKSPACE(d^nontblflapply)(showCOs,__CourseCOPair_list,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar10,__newvar1))))))))),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[fllibexecute_delayed_calls([__CO,__Course,__CourseCOPair,__CourseCOPair_list,__Course_CO_pair_list,__TeachingTimes],[__Course_CO_pair_list])],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?X',__X)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?X',__X)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',32,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(showCOsList,__X,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(=(__X,[]),nl),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?First',__First),=('?Course_CO_pair_list',__Course_CO_pair_list),=('?HM_Clashes',__HM_Clashes),=('?Rest',__Rest)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?First',__First),=('?Rest',__Rest)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',33,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(showCOsList,[__First|__Rest],'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(=(__First,','(__Course_CO_pair_list,__HM_Clashes)),','(FLORA_THIS_WORKSPACE(d^nontblflapply)(showCOs,__Course_CO_pair_list,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),','(writeln([with,__HM_Clashes,clashes]),','(writeln(**********************************),FLORA_THIS_WORKSPACE(d^nontblflapply)(showCOsList,__Rest,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar6,__newvar1)))))),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[fllibexecute_delayed_calls([__Course_CO_pair_list,__First,__HM_Clashes,__Rest],[__First,__Rest])],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TT_list',__TT_list)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TT_list',__TT_list)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',34,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(showTeachingTimes,__TT_list,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(=(__TT_list,[]),writeln(' ==== ')),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?TT',__TT),=('?Day',__Day),=('?Period',__Period),=('?TT_list',__TT_list)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?TT',__TT),=('?TT_list',__TT_list)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',35,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(showTeachingTimes,[__TT|__TT_list],'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(FLORA_WORKSPACE(m1,d^isa)(__TT,'RoomDayPeriodDuration','_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),','(','(FLORA_WORKSPACE(m1,d^mvd)(__TT,day,__Day,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar6,__newvar1)),FLORA_WORKSPACE(m1,d^mvd)(__TT,period,__Period,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar7,__newvar1))),','(write(-(-(__Day,__Period),' ')),FLORA_THIS_WORKSPACE(d^nontblflapply)(showTeachingTimes,__TT_list,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar8,__newvar1))))),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[fllibexecute_delayed_calls([__Day,__Period,__TT,__TT_list],[__TT,__TT_list])],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?COs',__COs),=('?CO',__CO),=('?Course',__Course)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?COs',__COs)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',36,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(showAllCOs,__COs,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(','(fllibsetof(__newdontcarevar7,[],','(','(FLORA_WORKSPACE(m1,d^isa)(__CO,'CourseOpening','_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),','(FLORA_WORKSPACE(m1,d^mvd)(__CO,ofCourse,__Course,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar6,__newvar1)),=(__newdontcarevar7,','(__Course,__CO)))),fllibexecute_delayed_calls([__CO,__Course,__newdontcarevar7],[])),__newvar8),=(__COs,__newvar8)),FLORA_THIS_WORKSPACE(d^nontblflapply)(showCOs,__COs,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar9,__newvar1))),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[fllibexecute_delayed_calls([__CO,__COs,__Course],[__COs])],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?R',__R)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?R',__R)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',37,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(isort,[],__R,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(=(__R,[]),!),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?T',__T),=('?Temp',__Temp),=('?H',__H),=('?Result',__Result)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?H',__H),=('?T',__T),=('?Result',__Result)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',38,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(isort,[__H|__T],__Result,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(FLORA_THIS_WORKSPACE(d^nontblflapply)(isort,__T,__Temp,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),FLORA_THIS_WORKSPACE(d^nontblflapply)(insert,__H,__Temp,__Result,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar6,__newvar1))),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[fllibexecute_delayed_calls([__H,__Result,__T,__Temp],[__H,__Result,__T])],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?R',__R),=('?X',__X)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?X',__X),=('?R',__R)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',39,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(insert,__X,[],__R,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(=(__R,[__X]),!),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?X',__X),=('?H',__H),=('?R',__R),=('?T',__T)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?X',__X),=('?H',__H),=('?T',__T),=('?R',__R)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',40,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(insert,__X,[__H|__T],__R,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(FLORA_THIS_WORKSPACE(d^nontblflapply)(is_smaller_or_equal,__X,__H,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),','(!,=(__R,[__X,__H|__T]))),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[null],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?X',__X),=('?T',__T),=('?Temp',__Temp),=('?R',__R),=('?H',__H)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?X',__X),=('?H',__H),=('?T',__T),=('?R',__R)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',41,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(insert,__X,[__H|__T],__R,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(FLORA_THIS_WORKSPACE(d^nontblflapply)(insert,__X,__T,__Temp,'_$ctxt'(FLORA_THIS_MODULE_NAME,__newcontextvar5,__newvar1)),=(__R,[__H|__Temp])),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[fllibexecute_delayed_calls([__H,__R,__T,__Temp,__X],[__H,__R,__T,__X])],true)])))).
?-(','(:(flrwhen,flora_put_attr(__newvar4,'\\$dynrule variable',[=('?F',__F),=('?HM1',__HM1),=('?S',__S),=('?HM2',__HM2)])),','(:(flrwhen,flora_put_attr(__newvar3,'\\$dynrule variable',[=('?F',__F),=('?S',__S)])),fllibinsertrule_z(FLORA_THIS_MODULE_NAME,[flsysruleupdate(__newvar1,dynrule('utilities.flr'),'_$_$_flora''descr_vars',42,['_$_$_flora''prop_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,type,rule,'_$_$_flora''descr_vars'),'_$_$_flora''tag_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,__newvar1,'_$_$_flora''descr_vars'),'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),'_$_$_flora''bool_descriptor'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME,strict,'_$_$_flora''descr_vars')],[FLORA_THIS_WORKSPACE(d^nontblflapply)(is_smaller_or_equal,__F,__S,'_$ctxt'(_DynRuleCallerModuleVar,__newvar1,__newcontextvar2))],','(=(__F,','(___CO_LIST1,__HM1)),','(=(__S,','(___CO_LIST2,__HM2)),fllibdelayedliteral(=<,'utilities.flr',200,[__HM1,__HM2]))),__newvar3,__newvar4,true,[null],[null],'_$_$_flora''rule_enabled'(__newvar1,dynrule('utilities.flr'),FLORA_THIS_MODULE_NAME),[fllibexecute_delayed_calls([__F,__HM1,__HM2,__S,___CO_LIST1,___CO_LIST2],[__F,__S])],true)])))).


%%%%%%%%%%%%%%%%%%%%%%%%% Signatures for latent queries %%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%




%%%%%%%%%%%%%%%%%%%%%%% Queries found in the source file %%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


 
#if !defined(FLORA_FLS2_FILENAME)
#if !defined(FLORA_LOADDYN_DATA)
#define FLORA_LOADDYN_DATA
#endif
#mode save
#mode nocomment "%"
#define FLORA_FLS2_FILENAME  'utilities.fls2'
#mode restore
?-(:(flrutils,flora_loaddyn_data(FLORA_FLS2_FILENAME,FLORA_THIS_MODULE_NAME,'fls2'))).
#else
#if !defined(FLORA_READ_CANONICAL_AND_INSERT)
#define FLORA_READ_CANONICAL_AND_INSERT
#endif
?-(:(flrutils,flora_read_symbols_canonical_and_insert(FLORA_FLS2_FILENAME,FLORA_THIS_FLS_STORAGE,_SymbolErrNum))).
#endif

